Enabling local API
henry-spanka/homebridge-buschjaeger pull request #59
Opened 2022-01-06 00:11 UTC by superyaro

Hallo Henry,

I added a local API Adaptor. There are a lot of changes/additions - we can walk it thru together if you want,

cheers 

Jaro

2022-01-08 16:05 UTC, henry-spanka requested changes
Thank you very much for your work. Please open a PR in the freeathome-api library project. We don't really need to make any changes to homebridge because internally it uses the library.

2022-01-08 16:05 UTC, henry-spanka commented on README.md
> +    "isLocalAPI": <true|false>,
I think we should detect the version of the SysAp and then automatically use the local API because the current implementation is kind of experimental too because there is no documentation or support from busch jaeger.

2022-01-10 17:29 UTC, superyaro commented on README.md
> +    "isLocalAPI": <true|false>,
Unfortunately I needed to make (some) changes in index.js and BuschJaegerAccessory.js (Data structure is slightly different) - for the local API calsses: it should come with another module then, since I didn't extended the Cloud API. something like "freeathome-api-local"

Regarding autodetect: what is with sysAP v1.x? Afaik they can run the newest firmware up to 3.x but cannot deliver the local API - I can try to autodetect SysAP version AND firmware version, what do you think? I'm running 3.0 with sysAP 2.0 - works very well,

J

2022-02-24 20:09 UTC, henry-spanka commented
Please make the pull request in the freeathome-api project. That way other projects can also use the Local API.

2022-04-19 21:54 UTC, closed without merging